name: Commit changes when FantasyData.xlsx changes

on:
  push:
    paths:
      - 'data/FantasyData.xlsx'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Commit and push if changed
      run: |
        git config --global user.email "parkert.geis@icloud.com"
        git config --global user.name "Parker Geis"
        git add data/FantasyData.xlsx
        timestamp=$(date -u)
        git commit -m "Changes made to FantasyData.xlsx at ${timestamp}" || exit 0
        git push
